name: packer

on:
  pull_request:
    branches: [ "main" ]

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer fmt validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init csye6225_packer/assign5-AMI.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate csye6225_packer/assign5-AMI.pkr.hcl"
